export interface Card {
  id: number
  tag: string
  question: string
  answer: string
}

export interface ChapterData {
  title: string
  cards: Card[]
}

export const chapters: Record<string, ChapterData> = {
  ch04: {
    title: '第4章 信息系统规划',
    cards: [
      { id: 1, tag: '否定辨析', question: '以下不属于信息系统规划六大原则的是（）。\nA、战略性\nB、整体性\nC、经济性\nD、遵从性', answer: '<p><strong>C、经济性</strong></p><p>六大原则口诀：<strong>战整先指柔遵</strong>——战略性、整体性、先进性、指导性、柔性、遵从性。经济性不属于规划原则，是系统设计原则。</p>' },
      { id: 2, tag: '特征归因', question: '信息系统规划时，满足组织数字化能力发展需求，体现了信息系统的（）。\nA、柔性\nB、先进性\nC、指导性\nD、遵从性', answer: '<p><strong>D、遵从性</strong></p><p>遵从性：需遵从法律法规、标准规范、组织战略与数字能力发展需求。这是首考真题原题。</p><p>易混淆点：<strong>柔性</strong>是适应内外部环境<strong>变化</strong>，而非遵从既有需求。</p>' },
      { id: 3, tag: '特征归因', question: '信息系统规划考虑技术发展趋势，融合内外部最佳实践，体现了六大原则中的（）。\nA、战略性\nB、先进性\nC、指导性\nD、柔性', answer: '<p><strong>B、先进性</strong></p><p>先进性：考虑技术趋势，融合内外部最佳实践。注意与<strong>战略性</strong>（与组织战略保持一致、驱动引领）区分。</p>' },
      { id: 4, tag: '排序分级', question: '信息系统规划的发展阶段（成熟度5级）从低到高分别是（）。\nA、打基础→提效率→做协同→构生态→强决策\nB、打基础→提效率→做协同→强决策→构生态\nC、提效率→打基础→做协同→强决策→构生态\nD、打基础→做协同→提效率→强决策→构生态', answer: '<p><strong>B</strong></p><p>口诀：<strong>打提做强构</strong></p><ol><li>一级·打基础：业务规范化、数字化意识、局部系统建设</li><li>二级·提效率：团队/部门职能、工作效率、全面推进系统建设</li><li>三级·做协同：数据共治共享、数据流优化业务流</li><li>四级·强决策：数据模型开发利用、决策效率效能、治理模式变革</li><li>五级·构生态：跨组织融合、云和互联网模式、广域协同</li></ol>' },
      { id: 5, tag: '场景匹配', question: '某大型制造企业已完成部门级系统建设，现需打破数据孤岛实现跨部门数据共享和业务协同。该企业应优先选择哪种信息系统框架？\nA、以应用功能为主线的框架\nB、以平台能力为主线的框架\nC、以互联网为主线的框架\nD、以上都不是', answer: '<p><strong>B、以平台能力为主线的框架</strong></p><p>场景关键词："打破数据孤岛""跨部门数据共享"→ 平层化建设、数据共享是<strong>平台能力主线</strong>的核心。</p><p>三种框架对比：</p><ul><li><strong>应用功能主线</strong>：中小型/信息化初期，"拿来主义"，竖井式</li><li><strong>平台能力主线</strong>：规模扩大期，平层化+数据共享+双态IT</li><li><strong>互联网主线</strong>：产业链/生态链阶段，App化微服务</li></ul><p>⚠️ 这是首考案例真题的出题方式：给场景选框架并说明理由。</p>' },
      { id: 6, tag: '场景匹配', question: '某集团企业已发展到产业链阶段，需要为不同成熟度的生态伙伴提供差异化服务，应选择哪种信息系统框架？\nA、以应用功能为主线的框架\nB、以平台能力为主线的框架\nC、以互联网为主线的框架\nD、以上都不是', answer: '<p><strong>C、以互联网为主线的框架</strong></p><p>关键词："产业链""生态伙伴""差异化服务"→ App化微服务、能力封装、成熟度差异适配。</p><p>局限：技术复杂度高。</p>' },
      { id: 7, tag: '否定辨析', question: '以下不属于信息系统规划七大体系的是（）。\nA、发展战略\nB、组织体系\nC、知识体系\nD、保障体系', answer: '<p><strong>C、知识体系</strong></p><p>七大体系口诀：<strong>发框组技任资保</strong>——发展战略、系统框架、组织体系、技术体系、任务体系、资源体系、保障体系。无"知识体系"。</p>' },
      { id: 8, tag: '特征归因', question: '技术体系定义中，"确保对关键技术的充分掌控"属于六大原则中的（）。\nA、可扩展性\nB、可驾驭性\nC、灵活性\nD、可靠性', answer: '<p><strong>B、可驾驭性</strong></p><p>可驾驭性：通过直接/间接/混合方式，确保充分掌控关键技术。</p><p>六大原则口诀：<strong>用安靠灵扩驾</strong></p>' },
      { id: 9, tag: '方法匹配', question: '请将以下描述与对应的规划方法匹配：\n（1）将组织战略集转换为信息系统战略集 → ？\n（2）自顶向下分析需求，自底向上设计结构 → ？\n（3）少数关键成功因素决定信息需求 → ？\n（4）价值链上识别战略环节优先部署IT → ？\n（5）6W×6层的企业架构分类 → ？', answer: '<p>口诀：<strong>战企关价扎</strong></p><ol><li><strong>SST</strong> 战略目标集转移（William King · 1978）</li><li><strong>BSP</strong> 企业系统规划（IBM · 1970s）</li><li><strong>CSF</strong> 关键成功因素（Zani/Rockart · 1970）</li><li><strong>VCA</strong> 价值链分析（Porter · 1985）</li><li><strong>Zachman</strong> 框架（John Zachman · 1987）</li></ol><p>⚠️ 首考案例真题出题方式：给描述写方法名。</p>' },
      { id: 10, tag: '否定辨析', question: '以下关于BSP企业系统规划法的说法，不正确的是（）。\nA、BSP的核心理念是管理功能应独立于组织机构\nB、BSP四个基本步骤依次是定义管理目标、定义管理功能、定义数据类、定义信息结构\nC、BSP定义数据类时只能使用实体法\nD、BSP定义信息结构时需构建功能/数据类矩阵进行聚类分组', answer: '<p><strong>C</strong></p><p>BSP定义数据类使用<strong>实体法+功能法</strong>两种，归纳10~20个数据类，并非只能用实体法。</p><p>BSP四步口诀：<strong>目功数构</strong>，核心理念：管理功能应独立于组织机构（组织变动不影响系统设计）。</p>' },
      { id: 11, tag: '内容产出物', question: '请填写信息系统规划中任务体系部署的六步过程及其产出：\n任务拆解 → ？ → ？ → ？ → ？ → ？', answer: '<p>口诀：<strong>任明匹制定监</strong></p><ol><li><strong>任务拆解</strong></li><li><strong>明确目标</strong> → 产出：SMA三层目标</li><li><strong>匹配组织</strong></li><li><strong>制定策略</strong></li><li><strong>定义计划</strong></li><li><strong>监控实施</strong></li></ol><p>SMA = Specific 具体 + Measurable 可测量 + Achievable 可实现</p>' },
      { id: 12, tag: '内容产出物', question: '请填写资源体系调度的四步过程：\n？ → ？ → ？ → ？', answer: '<p>口诀：<strong>识关分风</strong></p><ol><li><strong>资源识别与评估</strong></li><li><strong>资源关系与控制</strong></li><li><strong>资源分配与调度</strong></li><li><strong>资源风险与优化</strong></li></ol><p>资源识别可基于能力要素（人员/技术/流程/软硬件），也可基于「人机料法环测」六要素。</p>' },
      { id: 13, tag: '步骤默写', question: '信息系统规划工作要点（五步法）的完整流程是什么？', answer: '<p>口诀：<strong>内场深整持</strong></p><ol><li><strong>内外部需求挖掘</strong>：内5任务+5注意，外6任务+3注意</li><li><strong>场景化模型分析</strong>：8维度（场角业数技组风政）</li><li><strong>深度诊断与评估</strong>：成熟度模型5级+诊断3步</li><li><strong>整体与专项规划</strong>：7大体系全面规划</li><li><strong>持续改进</strong>：闭环迭代</li></ol><p>⚠️ 5个工作要点构成完整闭环，是案例题的高频考点。</p>' },
      { id: 14, tag: '特征归因', question: '深度诊断与评估中，"组织整体能力水平 = 最短板的能力水平状态"，这体现了什么原理？\nA、帕累托原理\nB、木桶原理\nC、墨菲定律\nD、戴明环', answer: '<p><strong>B、木桶原理</strong></p><p>诊断评估实施三步：①计划与打分（0/0.5/0.8/1四级） → ②权重与计算 → ③记录与确认（形成底稿，标注不满足项）</p><p>相关国标：GB/T 43439（数字转型成熟度）、GB/T 39116（智能制造成熟度）</p>' },
      { id: 15, tag: '场景匹配', question: '某企业信息化建设初期，以部门职能为单元分别采购ERP、CRM等成套软件。这种方式属于哪种框架？其局限性是什么？', answer: '<p><strong>以应用功能为主线的框架</strong></p><p>特征："拿来主义"、成套软件、按部门职能建设。</p><p>局限：系统间集成困难，形成竖井式信息孤岛。</p>' },
      { id: 16, tag: '否定辨析', question: '以下关于CSF关键成功因素法的说法，不正确的是（）。\nA、CSF的四个主要来源包括个别产业结构、竞争策略与产业地位、环境因素、暂时因素\nB、CSF四类包括内部型、外部型、监控型、建立型\nC、CSF实施四步为确定战略目标→识别所有成功因素→确定关键成功因素→识别绩效指标\nD、CSF认为所有成功因素同等重要，需全部满足', answer: '<p><strong>D</strong></p><p>CSF核心思想：<strong>少数关键成功因素决定信息需求</strong>，并非所有因素同等重要。CSF正是强调"关键"而非"全部"。</p><p>四个来源口诀：<strong>产竞环暂</strong>；四类：内部型/外部型/监控型/建立型。</p>' },
      { id: 17, tag: '方法匹配', question: 'VCA价值链分析法的四步应用分别是什么？', answer: '<p>四步应用：</p><ol><li>识别价值链</li><li>确定关键价值<strong>增加</strong>环节</li><li>确定关键价值<strong>减少</strong>环节</li><li>明确IT支持</li></ol><p>四个基本观点：价值核心 / 基本活动+支持活动 / 相互依存 / 竞争优势来自优化</p>' },
      { id: 18, tag: '特征归因', question: 'Zachman框架的6行×6列结构中，横向6W分别对应什么？纵向6层分别对应什么？', answer: '<p>结构：<strong>6行（纵向）× 6列（横向）= 36格</strong></p><p>横向<strong>6W</strong>：What（数据）/ How（功能）/ Where（网络）/ Who（人员）/ When（时间）/ Why（动机）</p><p>纵向<strong>6层</strong>：范围模型 → 企业模型 → 系统模型 → 技术模型 → 详细模型 → 功能模型</p>' },
      { id: 19, tag: '步骤默写', question: '内部需求挖掘的五项任务和五项注意事项分别是什么？', answer: '<p>五项任务（口诀：<strong>理熟收评感</strong>）：理解组织战略 / 熟悉业务流程 / 收集用户需求 / 评估现有系统 / 感知数字环境</p><p>五项注意事项（口诀：<strong>原避培谨隐</strong>）：以原始信息获取为主 / 避免直接给出解决方案 / 及时开展引导性培训 / 谨慎信息交叉传递 / 关注隐性需求的推演</p>' },
      { id: 20, tag: '步骤默写', question: '外部需求挖掘的六项任务和三项注意事项分别是什么？', answer: '<p>六项任务（口诀：<strong>国行技竞客标</strong>）：国家战略导入 / 行业趋势分析 / 技术趋势研究 / 竞争环境分析 / 客户期望调研 / 标准与规范引用</p><p>三项注意事项（口诀：<strong>国定避</strong>）：国家战略与政策引用 / 定性内容转定量对比 / 避免信息安全事件</p>' },
      { id: 21, tag: '综合辨析', question: '以下关于保障体系的说法，正确的是（）。\nA、保障体系仅涉及组织、人员和技术三方面\nB、数据方面包括数据治理能力、数据质量、数据标准化和数据开发\nC、安全方面只需关注安全技术，不需要安全管理体系\nD、人员方面强调专业技术人才的引进', answer: '<p><strong>B</strong></p><p>保障体系设定包括<strong>六个方面</strong>（不仅是三方面）：组织、人员、技术、资源、数据、安全。</p><p>B正确：数据方面 = 数据治理能力+数据质量+数据标准化+数据开发。</p><p>C错误：安全需安全意识+安全知识技能+安全管理体系。</p><p>D错误：人员方面强调<strong>全员数字能力培养</strong>，不是只引进专业人才。</p>' },
      { id: 22, tag: '场景匹配', question: '某企业各业务单元差异较大，需要各业务单元自行建设信息系统。应选择哪种组织体系模式？\nA、中小型\nB、集中式\nC、分权式\nD、平衡矩阵式', answer: '<p><strong>C、分权式</strong></p><p>四种组织体系模式：</p><ul><li><strong>中小型</strong>：中小企业，信息化管理委员会+信息化团队</li><li><strong>集中式</strong>：大型单位，专业信息部门、专职架构/质量/测试</li><li><strong>分权式</strong>：业务单元差异大，各业务单元自行建设、设统筹负责人</li><li><strong>平衡矩阵式</strong>：成熟度较高，稳态集中+敏态分权</li></ul>' },
    ]
  },

  ch05: {
    title: '第5章 应用系统规划',
    cards: [
      { id: 1, tag: '内容产出物', question: '应用系统规划的五大定义（主要内容）及其产出物分别是什么？', answer: '<p>口诀：<strong>生体接数构</strong></p><table><tr><th>内容</th><th>产出物</th></tr><tr><td>生命周期选择</td><td>生命周期模型</td></tr><tr><td>体系结构定义</td><td>整体视图</td></tr><tr><td>接口定义</td><td>通信方法、协议、接口调用方法、功能内容、输入/输出参数、错误/例外机制等</td></tr><tr><td>数据定义</td><td>数据模型和信息模型</td></tr><tr><td>构件定义</td><td>数据结构和构件</td></tr></table><p>⚠️ 这是首考案例真题的出题方式：问内容和产出物的对应关系。</p>' },
      { id: 2, tag: '场景匹配', question: '某项目需求明确且稳定，要求阶段间严格评审、推迟实现。应选择哪种生命周期模型？\nA、瀑布模型\nB、V模型\nC、迭代模型\nD、敏捷方法', answer: '<p><strong>A、瀑布模型</strong></p><p>四种生命周期模型口诀：<strong>瀑V迭敏</strong></p><ul><li><strong>瀑布</strong>：阶段间顺序依赖、推迟实现、每阶段评审，<strong>不适应需求变化</strong></li><li><strong>V模型</strong>：测试活动与分析/设计相关联，是瀑布变种</li><li><strong>迭代</strong>：演化/增量建设，缩短面世时间、失败风险低</li><li><strong>敏捷</strong>：4核心价值+12原则，快速响应变化</li></ul>' },
      { id: 3, tag: '否定辨析', question: '以下关于敏捷宣言的说法，不正确的是（）。\nA、个体和互动高于流程和工具\nB、工作的软件高于详尽的文档\nC、响应变化高于遵循计划\nD、流程和工具高于个体和互动', answer: '<p><strong>D</strong></p><p>敏捷宣言4种核心价值：</p><ol><li>个体和互动 <strong>高于</strong> 流程和工具</li><li>工作的软件 <strong>高于</strong> 详尽的文档</li><li>客户合作 <strong>高于</strong> 合同谈判</li><li>响应变化 <strong>高于</strong> 遵循计划</li></ol><p>D将优先级颠倒了。</p>' },
      { id: 4, tag: '否定辨析', question: '以下不属于应用系统规划9大基本概念的是（）。\nA、抽象\nB、模块化\nC、封装\nD、信息隐蔽', answer: '<p><strong>C、封装</strong></p><p>9大概念口诀：<strong>抽体模关模信功求重</strong>——抽象、体系架构、模式、关注点分离、模块化、信息隐蔽、功能独立、求精、重构。"封装"不在其中。</p>' },
      { id: 5, tag: '特征归因', question: '"每个模块隐蔽自己的规划设计决策（算法和数据）"，这属于哪个基本概念？\nA、模块化\nB、信息隐蔽\nC、功能独立\nD、关注点分离', answer: '<p><strong>B、信息隐蔽</strong></p><p>辨析：</p><ul><li><strong>信息隐蔽</strong>：每个模块<strong>隐蔽</strong>自己的规划设计决策（算法和数据）</li><li><strong>模块化</strong>：将系统<strong>划分</strong>为独立命名的、可处理的模块</li><li><strong>功能独立</strong>：通过<strong>专一功能、低耦合</strong>的模块实现</li><li><strong>关注点分离</strong>：将复杂问题<strong>分解</strong>为可独立解决的若干块</li></ul>' },
      { id: 6, tag: '特征归因', question: '功能独立的两个定性评估标准是什么？它们的关系是什么？', answer: '<ul><li><strong>内聚性</strong>：模块相关功能的强度（一个内聚模块应只完成一件/一类事情）</li><li><strong>耦合性</strong>：模块间的相互依赖性（应尽力得到最低耦合）</li></ul><p>关系：内聚性越高→独立性越高；耦合性越高→「涟漪效果」越严重</p><p>⚠️ 功能独立是良好规划设计的关键，规划设计又是应用系统质量的关键。</p>' },
      { id: 7, tag: '否定辨析', question: '以下关于体系架构模型的说法，不正确的是（）。\nA、框架模型通过确定相似应用中的可复用架构框架提高抽象级别\nB、动态模型强调架构行为方面，指明结构/配置随外部事件的变化\nC、过程模型表示系统的功能层次结构\nD、功能模型表示系统的功能层次结构', answer: '<p><strong>C</strong></p><p>四种模型口诀：<strong>框动过功</strong></p><ul><li><strong>框架模型</strong>：可复用架构框架提高抽象级别</li><li><strong>动态模型</strong>：架构行为、结构/配置随外部事件变化</li><li><strong>过程模型</strong>：系统必须提供的<strong>业务或技术流程设计</strong>（不是功能层次结构）</li><li><strong>功能模型</strong>：表示系统的<strong>功能层次结构</strong></li></ul><p>C和D混淆了过程模型与功能模型。</p>' },
      { id: 8, tag: '否定辨析', question: '以下关于SOA面向服务架构的说法，不正确的是（）。\nA、SOA通过定义良好的接口和契约联系功能单元\nB、SOA主要适用场景包括业务流程管理和跨平台集成\nC、SOA适合技术驱动业务的场景\nD、SOA六大设计原则包括明确的接口定义、粗粒度、松耦合', answer: '<p><strong>C</strong></p><p>SOA适用场景（口诀：<strong>集流扩云跨</strong>）：组织级应用集成 / 业务流程管理 / 系统扩展和重用 / 云计算和微服务 / 跨平台集成。</p><p><strong>不适用"技术驱动业务"</strong>——SOA是业务驱动的架构思想，不是技术驱动。</p><p>⚠️ 这是首考真题原题：Q20"SOA主要适用的场景不包括技术驱动业务"。</p>' },
      { id: 9, tag: '步骤默写', question: '详细调研的步骤有哪些？', answer: '<p>6大步骤：</p><ol><li>收集信息</li><li>系统需求建模</li><li>需求的优先级划分</li><li>构建系统原型，检验可行性并发现问题</li><li>产生和评估候选方案</li><li>和管理部门一起复查各种建议</li></ol><p>⚠️ 这是首考案例真题原题（案例一Q1）。</p>' },
      { id: 10, tag: '方法匹配', question: '请将以下描述与对应的需求分析方法匹配：\n（1）自顶向下、逐层分解，核心模型=数据流图 → ？\n（2）以数据为中心，核心模型=实体关系图 → ？\n（3）兼顾功能+数据，核心模型=用例图+领域类图 → ？\n（4）最轻量级，核心模型=用户故事 → ？', answer: '<p>口诀：<strong>结信U敏</strong></p><ol><li><strong>面向过程的结构化方法</strong></li><li><strong>面向数据的信息工程方法</strong></li><li><strong>基于UML的用例驱动方法</strong></li><li><strong>基于敏捷的用户故事</strong></li></ol>' },
      { id: 11, tag: '步骤默写', question: '应用系统主要过程（五步法）是什么？', answer: '<p>口诀：<strong>初可详分设</strong></p><ol><li><strong>初步调研</strong>：5方面（口诀：<strong>组环现态资</strong>）</li><li><strong>可行性研究</strong>：4方面（口诀：<strong>经技社管</strong>）</li><li><strong>详细调研</strong>：6原则+5方法</li><li><strong>系统分析</strong>：3阶段（问题分析→需求分析→需求定义）</li><li><strong>系统设计</strong>：2阶段（总体设计→详细设计）</li></ol><p>⚠️ 5个过程构成完整系统建设链路，是案例和论文的高频考点。</p>' },
      { id: 12, tag: '特征归因', question: '可行性研究中，"领导是否支持？管理人员是否配合？组织能否接受变革？"属于哪方面的分析？\nA、经济可行性\nB、技术可行性\nC、社会可行性\nD、管理可行性', answer: '<p><strong>D、管理可行性</strong></p><p>四种可行性口诀：<strong>经技社管</strong></p><ul><li><strong>经济可行性</strong>：是否值得建设？总成本 vs 总收益</li><li><strong>技术可行性</strong>：技术资源可用吗？优选成熟技术</li><li><strong>社会可行性</strong>：与社会环境相符吗？政策/法律/道德/制度</li><li><strong>管理可行性</strong>：领导支持吗？管理人员配合度、变革接受度</li></ol><p>三种结论：①可行 ②基本可行需修改 ③不可行不立项</p>' },
      { id: 13, tag: '方法匹配', question: '请将以下描述与对应的常用方法匹配：\n（1）评估和管理组织应用系统，确定保留/更新/替换/淘汰 → ？\n（2）ADM全生命周期10阶段+三级迭代 → ？\n（3）通过定义良好的接口和契约联系功能单元 → ？', answer: '<p>口诀：<strong>组框务</strong></p><ol><li><strong>APA 应用系统组合法</strong>，六步（口诀：<strong>清评分策实监</strong>）</li><li><strong>TOGAF 开放组架构框架</strong>，六组件（口诀：<strong>A指内连参能</strong>）</li><li><strong>SOA 面向服务的架构</strong>，六设计原则+六技术内容</li></ol>' },
      { id: 14, tag: '步骤默写', question: 'TOGAF ADM全生命周期10阶段分别是什么？', answer: '<p>核心=ADM（架构开发方法），贯穿<strong>需求管理</strong></p><ol><li><strong>预备阶段</strong>：定义组织/架构框架/原则/工具</li><li><strong>A.架构愿景</strong>：设定范围/约束/期望</li><li><strong>B.业务架构</strong>：基线/目标架构描述+差距分析</li><li><strong>C.信息系统架构</strong>：应用架构+数据架构</li><li><strong>D.技术架构</strong>：技术层面架构开发</li><li><strong>E.机会和解决方案</strong>：初步实施规划</li><li><strong>F.迁移规划</strong>：详细实施和迁移计划</li><li><strong>G.实施治理</strong>：架构监督，监测实施</li><li><strong>H.架构变更治理</strong>：持续监测和变更管理</li></ol><p>ADM三级迭代：①整体迭代 ②多阶段间迭代 ③单阶段内部迭代</p>' },
      { id: 15, tag: '否定辨析', question: '以下关于SOA六大设计原则的说法，不正确的是（）。\nA、服务应具有明确的接口定义\nB、服务应是细粒度的，以提供更精细的控制\nC、服务之间应保持松耦合\nD、服务应是自包含与模块化的', answer: '<p><strong>B</strong></p><p>SOA六大设计原则（口诀：<strong>明自粗松互策</strong>）：明确的接口定义 / 自包含与模块化 / <strong>粗粒度</strong> / 松耦合 / 互操作性兼容性策略声明。</p><p>B错：SOA强调<strong>粗粒度</strong>而非细粒度，粗粒度减少调用次数、提高效率。</p>' },
      { id: 16, tag: '特征归因', question: '界面设计的三大黄金原则中，"不强迫不必要动作、灵活交互、可中断撤销"属于哪个原则？\nA、置用户于控制之下\nB、减少用户记忆负担\nC、保持界面一致\nD、关注点分离', answer: '<p><strong>A、置用户于控制之下</strong></p><p>三大原则口诀：<strong>控记一</strong></p><ul><li><strong>置用户于控制之下</strong>：不强迫不必要动作、灵活交互、可中断撤销</li><li><strong>减少用户记忆负担</strong>：减少短期记忆、有意义的默认值、现实世界隐喻</li><li><strong>保持界面一致</strong>：保持语境、不改变已有交互模式</li></ul>' },
      { id: 17, tag: '内容产出物', question: '数据库定义的5步骤及其各步产出分别是什么？', answer: '<p>口诀：<strong>需概逻物验</strong></p><ol><li><strong>需求分析</strong> → 用户需求规约</li><li><strong>概念模型</strong> → 概念数据模型（E-R图）</li><li><strong>逻辑模型</strong> → 逻辑数据模式</li><li><strong>物理数据库</strong> → 物理存储结构/存取方法</li><li><strong>验证</strong> → 验证正确性和合理性</li></ol>' },
      { id: 18, tag: '否定辨析', question: '以下关于系统设计的说法，不正确的是（）。\nA、系统设计分为总体设计和详细设计两个阶段\nB、五大评价指标包括可靠性、可变更性、效率、通用性、工作质量\nC、五大设计原则包括系统性、灵活性、可靠性、经济性、管理可接受\nD、系统设计时应优先追求效率指标，其他指标次之', answer: '<p><strong>D</strong></p><p>五大评价指标（口诀：<strong>可靠可变效通质</strong>）和五大设计原则（口诀：<strong>系灵可经管</strong>）需平衡兼顾，不存在"效率优先"的原则。</p><p>设计原则中<strong>可靠性</strong>和<strong>经济性</strong>需要权衡，而非某一项绝对优先。</p>' },
      { id: 19, tag: '特征归因', question: '将复杂业务活动转化为可管控、可显性表达、可重用的业务区块，聚焦价值本质。这属于哪种抽象类型？\nA、业务抽象\nB、过程抽象\nC、数据抽象\nD、技术抽象', answer: '<p><strong>A、业务抽象</strong></p><p>四种抽象口诀：<strong>业过数技</strong></p><ul><li><strong>业务抽象</strong>：复杂业务→可管控可重用业务区块，聚焦价值</li><li><strong>过程抽象</strong>：指令序列，暗示功能但隐藏细节</li><li><strong>数据抽象</strong>：数据对象的属性完整定义</li><li><strong>技术抽象</strong>：可持续开发利用的技术体系</li></ul>' },
      { id: 20, tag: '场景匹配', question: '某企业需要对现有应用系统进行评估，确定哪些保留、哪些更新、哪些替换、哪些淘汰。应采用哪种方法？\nA、TOGAF\nB、APA\nC、SOA\nD、BSP', answer: '<p><strong>B、APA应用系统组合法</strong></p><p>APA六步（口诀：<strong>清评分策实监</strong>）：清查现有系统 → 评估系统价值 → 分析系统差距 → 制定策略（保留/更新/替换/淘汰） → 实施变更 → 监控和调整</p>' },
      { id: 21, tag: '综合辨析', question: '以下关于软件工厂的说法，正确的是（）。\nA、软件工厂的特点包括敏捷交付、流水线作业、安全可靠、协同开发\nB、软件工厂仅包含工具和技术一个构成要素\nC、软件工厂建设四支柱包括组织建设、资源部署、业务管理、体系保障\nD、A和C都正确', answer: '<p><strong>D</strong></p><p>四大特点口诀：<strong>敏流安协</strong>：敏捷交付 / 流水线作业 / 安全可靠 / 协同开发</p><p>五大构成口诀：<strong>人基工流质</strong>：专业人员 / 基础设施和硬件 / 工具和技术 / 流程规范和方法论 / 质量管理</p><p>建设四支柱口诀：<strong>组资业体</strong>：组织建设 / 资源部署 / 业务管理 / 体系保障</p>' },
      { id: 22, tag: '步骤默写', question: '详细调研的6大原则和5种方法分别是什么？', answer: '<p>6大原则（口诀：<strong>自用分工全主</strong>）：自顶向下全面展开 / 用户参与 / 分析改进可能性 / 工程化工作方式 / 全面与重点相结合 / 主动沟通和友善工作方式</p><p>5种方法（口诀：<strong>收发开访深</strong>）：收集资料 / 发调研表 / 开调研会 / 访问 / 深入实际</p>' },
    ]
  },

  ch06: {
    title: '第6章 云资源规划',
    cards: [
      { id: 1, tag: '场景匹配', question: '某企业业务发展较快，需要大量基础设施，应选择哪种云计算服务模式？\nA、IaaS\nB、PaaS\nC、SaaS\nD、FaaS', answer: '<p><strong>A、IaaS</strong></p><p>关键词"需要大量基础设施"→ IaaS提供虚拟化计算资源。</p><p>⚠️ 这是首考案例真题（案例二Q3-1）的原题。</p>' },
      { id: 2, tag: '场景匹配', question: '某企业开发人员需要方便地编写代码和部署应用，应选择哪种云计算服务模式？\nA、IaaS\nB、PaaS\nC、SaaS\nD、FaaS', answer: '<p><strong>D、FaaS</strong>（功能即服务）</p><p>开发人员"方便写代码和部署"→ FaaS将功能拆分为独立可复用函数，最适合快速开发部署。</p><p>⚠️ 这是首考案例真题（案例二Q3-2）的变体。原题答案为SaaS，但"写代码"场景更适合FaaS/PaaS。真题需结合具体场景判断。</p>' },
      { id: 3, tag: '场景匹配', question: '某企业需要性能较高的计算资源（如大数据、AI训练），应选择哪种计算资源形态？\nA、虚拟机\nB、容器\nC、裸金属\nD、GPU', answer: '<p><strong>C、裸金属</strong></p><p>关键词"高性能"→ 裸金属以物理机形态提供，面向数据库/大数据/AI等高性能场景。</p><p>⚠️ 这是首考真题（Q18/Q27）的考点："云服务以物理机提供计算服务"= 裸金属。</p>' },
      { id: 4, tag: '场景匹配', question: '请将以下场景与对应的云计算服务模式匹配：\n（1）业务发展快，需大量基础设施 → ？\n（2）需要文档协作平台 → ？\n（3）需要文档上传功能 → ？', answer: '<ol><li><strong>IaaS</strong>（基础设施即服务）</li><li><strong>PaaS</strong>（平台即服务）</li><li><strong>FaaS</strong>（功能即服务）</li></ol><p>⚠️ 这是首考案例真题（案例二Q3）的完整考法。</p>' },
      { id: 5, tag: '计算应用', question: '某前端服务器配置8vCPU，当前运行300个实例，CPU使用率50%。三年后业务量翻倍，资源线性增长，CPU利用率目标80%，求三年后的vCPU总量和实例数量。', answer: '<p>当前前端CPU使用量 = 8 × 300 × 50% = <strong>1200 vCPU</strong></p><p>三年后业务翻倍：1200 × 2 = <strong>2400 vCPU</strong></p><p>目标利用率80%：2400 / 0.8 = <strong>3000 vCPU</strong></p><p>实例数 = 3000 / 8 = <strong>375台</strong></p><p>⚠️ 这是首考案例真题（案例一Q2）的完整计算过程。</p>' },
      { id: 6, tag: '方法匹配', question: '请将以下描述与对应的计算资源规划方法匹配：\n（1）基于历史数据和趋势分析，预测未来资源需求 → ？\n（2）优化资源配置和使用，提高系统性能和效率 → ？\n（3）将工作负载分布到多个资源，确保均衡高效 → ？\n（4）根据实际需求变化自动扩展或收缩资源 → ？', answer: '<ol><li><strong>容量规划</strong></li><li><strong>性能优化</strong></li><li><strong>负载均衡</strong></li><li><strong>弹性伸缩</strong></li></ol><p>⚠️ 这是首考案例真题（案例一Q3）的原题。</p>' },
      { id: 7, tag: '否定辨析', question: '以下不属于云计算五大内部特征的是（）。\nA、虚拟化\nB、弹性扩展\nC、成本效益\nD、多租户支持', answer: '<p><strong>C、成本效益</strong></p><p>成本效益属于四大<strong>外部</strong>特征，不是内部特征。</p><p>五大内部特征（口诀：<strong>虚弹自多编</strong>）：虚拟化 / 弹性扩展 / 自动化管理 / 多租户支持 / 资源编排和管理</p><p>四大外部特征（口诀：<strong>可安网成</strong>）：可靠性和可用性 / 安全性 / 网络连接性 / 成本效益</p>' },
      { id: 8, tag: '否定辨析', question: '以下不属于混合云关键能力的是（）。\nA、服务门户统一\nB、资源监控界面统一\nC、账户权限统一\nD、所有数据必须存储在公有云', answer: '<p><strong>D</strong></p><p>混合云关键能力：提供<strong>统一的服务体验</strong>——服务门户统一、资源监控界面统一、账户权限统一。</p><p>不是简单叠加，更不是所有数据存公有云。混合云的核心是公有+私有<strong>协同</strong>，灵活分配。</p>' },
      { id: 9, tag: '特征归因', question: '云服务提供商以物理机形态提供云计算服务，主要面向数据库、大数据、AI等对计算性能要求较高的场景。这是指哪种计算资源形态？\nA、虚拟机\nB、容器\nC、裸金属\nD、GPU', answer: '<p><strong>C、裸金属</strong></p><p>⚠️ 这是首考真题（Q18/Q27）原题："以物理机提供计算服务"= 裸金属。</p><p>五种形态口诀：<strong>虚容裸G弹</strong>：虚拟机 / 容器 / 裸金属 / GPU / 弹性计算资源</p>' },
      { id: 10, tag: '计算应用', question: '某应用服务器配置16vCPU，当前运行200个实例，CPU使用率60%。三年后业务量翻倍，CPU利用率目标80%，求三年后的vCPU总量和实例数量。', answer: '<p>当前CPU使用量 = 16 × 200 × 60% = <strong>1920 vCPU</strong></p><p>三年后翻倍：1920 × 2 = <strong>3840 vCPU</strong></p><p>目标利用率80%：3840 / 0.8 = <strong>4800 vCPU</strong></p><p>实例数 = 4800 / 16 = <strong>300台</strong></p><p>⚠️ 这是首考案例真题（案例一Q2）应用服务器的计算过程。</p>' },
      { id: 11, tag: '排序分级', question: '云数据中心的国际分级标准TIA-942从高到低分别是（）。\nA、T1→T2→T3→T4\nB、T4→T3→T2→T1\nC、T3→T4→T1→T2\nD、T2→T1→T4→T3', answer: '<p><strong>B</strong>（从高到低）</p><p>分级标准：</p><ul><li><strong>国内</strong>：GB 50174 → A/B/C 三级（A最高）</li><li><strong>国际</strong>：TIA-942 → T4/T3/T2/T1 四级（T4最高）</li></ul>' },
      { id: 12, tag: '计算应用', question: 'PUE是什么？计算公式是什么？某数据中心总用电量1500kW，IT设备用电量1000kW，PUE是多少？是否达标？', answer: '<p><strong>PUE（电能使用效率）</strong> = 数据中心总用电量 / IT设备总用电量</p><p>计算：PUE = 1500 / 1000 = <strong>1.5</strong></p><p>PUE越接近<strong>1</strong>越好（IT能耗占比100%，无额外浪费）。</p><p>1.5属于一般水平，优秀数据中心PUE应≤1.2。</p><p>⚠️ 首考案例出现纯计算题，PUE计算是重点。</p>' },
      { id: 13, tag: '否定辨析', question: '以下关于边缘计算特点的说法，不正确的是（）。\nA、联接性\nB、数据第一入口\nC、弹性计算\nD、约束性', answer: '<p><strong>C、弹性计算</strong></p><p>边缘计算特点包括：联接性、数据第一入口、约束性、分布性。<strong>不包括弹性计算</strong>（弹性计算是云计算的特征）。</p><p>⚠️ 这是首考真题（Q13）原题。</p>' },
      { id: 14, tag: '方法匹配', question: '请将以下描述与对应的存储类型匹配：\n（1）直连主机/服务器，高性能，适合小型环境 → ？\n（2）网络协议文件级访问，适合文件共享/备份 → ？\n（3）专用网络块级存储，适合企业级高性能 → ？\n（4）分布式、高扩展性，适合大规模数据 → ？', answer: '<p>口诀：<strong>D N S 对云分虚</strong></p><ol><li><strong>DAS</strong>（直接附加存储）</li><li><strong>NAS</strong>（网络附加存储）</li><li><strong>SAN</strong>（存储区域网络）</li><li><strong>对象存储</strong></li></ol><p>其余三种：云存储 / 分布式文件系统 / 虚拟化存储</p>' },
      { id: 15, tag: '内容产出物', question: '云数据中心的四大规划目标、五大要素和七大设计原则分别是什么？', answer: '<p>四目标（口诀：<strong>可扩效安</strong>）：可靠性和可用性 / 可扩展性 / 性能和效率 / 安全和合规性</p><p>五要素（口诀：<strong>面资高按低</strong>）：面向服务 / 资源池化 / 高效智能 / 按需供给 / 低碳环保</p><p>七原则（口诀：<strong>可冗弹性优安灵节扩</strong>）：可用性和冗余性 / 弹性和可扩展性 / 性能优化 / 安全和隐私 / 灵活性和可管理性 / 节能和环保 / 高度可扩展的存储和网络架构</p>' },
      { id: 16, tag: '场景匹配', question: '某企业需要将计算能力下沉到靠近数据源的位置，采用"云计算+边缘计算"模式。这属于云数据中心哪个功能定位方向？\nA、城市数据中心\nB、边缘数据中心\nC、数据中心和网络协同\nD、国际化数据中心', answer: '<p><strong>B、边缘数据中心</strong></p><p>四个方向口诀：<strong>城边网国</strong></p><ul><li><strong>城市数据中心</strong>：向实时性和弹性化发展，需异地灾备</li><li><strong>边缘数据中心</strong>：计算能力下沉，"云计算+边缘计算"模式</li><li><strong>数据中心和网络协同</strong>：云网边深度融合的算力网络</li><li><strong>国际化数据中心</strong>：自贸区/"一带一路"沿线试点</li></ul>' },
      { id: 17, tag: '综合辨析', question: '以下关于云资源规划的说法，正确的是（）。\nA、云资源规划五步流程是一次性完成的\nB、预算管理是云资源规划七大关键要素之一\nC、公有云的数据安全性高于私有云\nD、FaaS的主要用户是系统管理员', answer: '<p><strong>B</strong></p><p>A错误：五步流程（口诀：<strong>收评预设优</strong>）是<strong>循环过程</strong>，不是一次性完成。</p><p>B正确：七大要素（口诀：<strong>需评预安弹优监</strong>）包括预算管理。</p><p>C错误：私有云数据安全性高于公有云。</p><p>D错误：FaaS主要用户是<strong>开发人员</strong>，IaaS的主要用户才是系统管理员。</p>' },
      { id: 18, tag: '特征归因', question: '四种虚拟化技术中，"OS无须修改，兼容性好"是哪种技术的特点？\nA、硬件仿真技术\nB、全虚拟化技术\nC、半虚拟化技术\nD、硬件辅助虚拟化技术', answer: '<p><strong>B、全虚拟化技术</strong></p><p>四种技术口诀：<strong>硬全半辅</strong></p><ul><li><strong>硬件仿真</strong>：在宿主机OS上创建硬件VM仿真所需硬件</li><li><strong>全虚拟化</strong>：软件模拟与真实硬件完全相同的环境，<strong>OS无须修改，兼容性好</strong></li><li><strong>半虚拟化</strong>：暴露修改过的硬件抽象，以软件形式提供硬件接口</li><li><strong>硬件辅助虚拟化</strong>：借助CPU/芯片组/IO设备虚拟化支持实现高效全虚拟化</li></ul>' },
      { id: 19, tag: '步骤默写', question: '计算资源规划的七步关键过程是什么？', answer: '<p>口诀：<strong>需容服虚安本监</strong></p><ol><li>需求分析</li><li>容量规划</li><li>云服务选择</li><li>虚拟化策略</li><li>安全性考虑</li><li>成本效益分析</li><li>持续监控维护</li></ol>' },
      { id: 20, tag: '内容产出物', question: '网络性能测试的三个层次分别测试哪些指标？', answer: '<ul><li><strong>网络层</strong>：连通性、带宽、时延、丢包率</li><li><strong>传输层</strong>：丢包率、吞吐量、连接数</li><li><strong>应用层</strong>：页面丢失率、应答延迟、吞吐量</li></ul><p>两种测试方法：</p><ul><li><strong>主动测试</strong>：部署测试工具，主动发送探测流 → 适合端到端时延、丢包</li><li><strong>被动测试</strong>：被动采集数据 → 适合路径吞吐量等流量参数</li></ul>' },
    ]
  }
}
