export interface Card {
  id: number
  tag: string
  question: string
  answer: string
}

export interface ChapterData {
  title: string
  cards: Card[]
}

export const chapters: Record<string, ChapterData> = {
  ch04: {
    title: '第4章 信息系统规划',
    cards: [
      { id: 1, tag: '必须掌握', question: '信息系统规划的定义是什么？由谁负责、用什么方法、输出什么？', answer: '<p>组织<strong>决策层</strong>任主要负责人，<strong>管理层</strong>为工作主体，使用<strong>自顶向下分解</strong> / <strong>自底向上聚合</strong>，确定信息系统的整体<strong>发展战略</strong>、<strong>总体框架</strong>、<strong>演进路径</strong>和<strong>资源分配策略</strong>。</p>' },
      { id: 2, tag: '必须掌握', question: '信息系统规划的六大原则是什么？请说出记忆口诀。', answer: '<p>口诀：<strong>战整先指柔遵</strong></p><ul><li><strong>战略性</strong>：与组织战略保持一致，驱动引领组织建设</li><li><strong>整体性</strong>：业务赋能、系统框架、建设实施、集成融合四个方面</li><li><strong>先进性</strong>：考虑技术趋势，融合内外部最佳实践</li><li><strong>指导性</strong>：从业务需求、技术方案、实施管理、成本控制等方面给出框架性要求</li><li><strong>柔性</strong>：满足对内外部环境变化的适应性</li><li><strong>遵从性</strong>：法律法规、标准规范、组织战略与数字能力发展需求</li></ul>' },
      { id: 3, tag: '必须掌握', question: '信息系统规划七大体系有哪些？请说出记忆口诀。', answer: '<p>口诀：<strong>发框组技任资保</strong></p><ul><li><strong>发展战略</strong>（发）：目标树 / 5级成熟度 / 发展路径</li><li><strong>系统框架</strong>（框）：应用功能→平台能力→互联网主线</li><li><strong>组织体系</strong>（组）：中小型 / 集中式 / 分权式 / 平衡矩阵</li><li><strong>技术体系</strong>（技）：6原则 / 技术蓝图两种图</li><li><strong>任务体系</strong>（任）：拆解→目标→组织→策略→计划→监控</li><li><strong>资源体系</strong>（资）：识别评估→关系控制→分配调度→风险优化</li><li><strong>保障体系</strong>（保）：组织 / 人员 / 技术 / 资源 / 数据 / 安全</li></ul>' },
      { id: 4, tag: '高频考点', question: '五个发展阶段（成熟度5级）分别是什么？请说出记忆口诀和每级核心。', answer: '<p>口诀：<strong>打提做强构</strong></p><ul><li><strong>一级·打基础</strong>：业务规范化、数字化意识、局部系统建设</li><li><strong>二级·提效率</strong>：团队/部门职能、工作效率、全面推进系统建设</li><li><strong>三级·做协同</strong>：数据共治共享、数据流优化业务流、多元协同</li><li><strong>四级·强决策</strong>：数据模型开发利用、决策效率效能、治理模式变革</li><li><strong>五级·构生态</strong>：跨组织融合、云和互联网模式、广域协同</li></ul>' },
      { id: 5, tag: '高频考点', question: '三种框架演进路径的适用阶段和核心理念分别是什么？', answer: '<ul><li><strong>以应用功能为主线</strong>：适用中小型/信息化初期，"拿来主义"、成套软件、按部门职能建设，局限是系统间集成困难</li><li><strong>以平台能力为主线</strong>：适用规模扩大/个性化需求，平层化建设、数据共享、双态IT（稳态+敏态），局限是无法包容生态伙伴差异</li><li><strong>以互联网为主线</strong>：适用产业链/生态链阶段，App化微服务、能力封装、成熟度差异适配，局限是技术复杂度高</li></ul>' },
      { id: 6, tag: '高频考点', question: '四种组织体系模式及其适用对象是什么？', answer: '<ul><li><strong>中小型</strong>：中小企业，信息化管理委员会 + 信息化团队</li><li><strong>集中式</strong>：大型单位，专业信息部门、最高管理者第一责任人、专职架构/质量/测试人员</li><li><strong>分权式</strong>：业务单元差异大，各业务单元自行建设、设统筹负责人或虚拟团队</li><li><strong>平衡矩阵式</strong>：成熟度较高，稳态集中建设 + 敏态分权管理，业务侧重数据开发</li></ul>' },
      { id: 7, tag: '高频考点', question: '技术体系定义的六大原则是什么？请说出记忆口诀。', answer: '<p>口诀：<strong>用安靠灵扩驾</strong></p><ul><li><strong>可用性</strong>：不是二元（行/不行），是可用程度的问题，需多维度排序</li><li><strong>安全性</strong>：安全漏洞认知 + 故障影响最小 + 与信息安全管理体系匹配</li><li><strong>可靠性</strong>：三方面考察——成熟性、技术整体性、技术风险性</li><li><strong>灵活性</strong>：技术组件化 + 技术组合架构，少量变化满足新需求</li><li><strong>可扩展性</strong>：韧性拓展，适应更多用户/业务/数据/交互</li><li><strong>可驾驭性</strong>：直接/间接/混合方式，确保充分掌控关键技术</li></ul>' },
      { id: 8, tag: '高频考点', question: '任务体系部署的六步过程是什么？口诀和三层目标原则？', answer: '<p>口诀：<strong>任明匹制定监</strong></p><p>六步：<strong>任务拆解</strong> → <strong>明确目标</strong> → <strong>匹配组织</strong> → <strong>制定策略</strong> → <strong>定义计划</strong> → <strong>监控实施</strong></p><p>三层目标原则：<strong>S</strong>pecific 具体 + <strong>M</strong>easurable 可测量 + <strong>A</strong>chievable 可实现</p>' },
      { id: 9, tag: '高频考点', question: '资源体系调度的四步过程是什么？资源识别可基于哪些要素？', answer: '<p>口诀：<strong>识关分风</strong></p><p>四步：<strong>资源识别与评估</strong> → <strong>资源关系与控制</strong> → <strong>资源分配与调度</strong> → <strong>资源风险与优化</strong></p><p>资源识别：可基于能力要素（人员/技术/流程/软硬件），也可基于「人机料法环测」六要素。</p>' },
      { id: 10, tag: '高频考点', question: '保障体系设定的六个方面分别是什么？', answer: '<ul><li><strong>组织</strong>：决策层承诺、组织变革支持、思想认识一致性</li><li><strong>人员</strong>：全员数字能力培养、变革接受预期、碎片化时间利用</li><li><strong>技术</strong>：储备预研、微创新鼓励、标准化驱动</li><li><strong>资源</strong>：软实力建设、云服务获取硬资源、优先级提升</li><li><strong>数据</strong>：数据治理能力、数据质量、数据标准化、数据开发</li><li><strong>安全</strong>：安全意识、安全知识技能、安全管理体系</li></ul>' },
      { id: 11, tag: '五星重要', question: '信息系统规划工作要点（五步法）是什么？请说出记忆口诀。', answer: '<p>口诀：<strong>内场深整持</strong></p><p>五步递进：<strong>内外部需求挖掘</strong> → <strong>场景化模型分析</strong> → <strong>深度诊断与评估</strong> → <strong>整体与专项规划</strong> → <strong>持续改进</strong></p><p>⚠️ 5个工作要点构成一个完整闭环，是案例题的高频考点。</p>' },
      { id: 12, tag: '高频考点', question: '内部需求挖掘的五项任务和五项注意事项分别是什么？', answer: '<p>五项任务（口诀：<strong>理熟收评感</strong>）：理解组织战略 / 熟悉业务流程 / 收集用户需求 / 评估现有系统 / 感知数字环境</p><p>五项注意事项（口诀：<strong>原避培谨隐</strong>）：以原始信息获取为主 / 避免直接给出解决方案 / 及时开展引导性培训 / 谨慎信息交叉传递 / 关注隐性需求的推演</p>' },
      { id: 13, tag: '高频考点', question: '外部需求挖掘的六项任务和三项注意事项分别是什么？', answer: '<p>六项任务（口诀：<strong>国行技竞客标</strong>）：国家战略导入 / 行业趋势分析 / 技术趋势研究 / 竞争环境分析 / 客户期望调研 / 标准与规范引用</p><p>三项注意事项（口诀：<strong>国定避</strong>）：国家战略与政策引用 / 定性内容转定量对比 / 避免信息安全事件</p>' },
      { id: 14, tag: '高频考点', question: '场景化模型分析的八维度是什么？请说出记忆口诀。', answer: '<p>口诀：<strong>场角业数技组风政</strong></p><ul><li><strong>场景</strong>定义：目标、范围、业务背景、利益相关者</li><li><strong>角色</strong>分析：职责、需求、行为、作用与影响</li><li><strong>业务</strong>分析：业务模式、流程、需求、发展</li><li><strong>数据</strong>分析：数据流、数据来源/类型/结构、开发利用价值</li><li><strong>技术</strong>分析：管理/工艺/决策/信息技术现状与发展</li><li><strong>组织</strong>分析：组织文化、人员技能、组织流程</li><li><strong>风险</strong>分析：技术/安全/管理风险与应对策略</li><li><strong>政策与法律</strong>分析：合规性分析</li></ul>' },
      { id: 15, tag: '高频考点', question: '深度诊断与评估的核心工具是什么？诊断评估实施有哪三步？', answer: '<p>核心工具：<strong>成熟度模型（5级）</strong></p><p>相关国标：GB/T 43439（数字转型成熟度）、GB/T 39116（智能制造成熟度）</p><p>诊断评估实施三步：</p><ol><li><strong>计划与打分</strong>：0分/0.5分/0.8分/1分四级打分，由低到高逐级</li><li><strong>权重与计算</strong>：参考标准或自动设定</li><li><strong>记录与确认</strong>：形成底稿，标注不满足项，获得干系人确认</li></ol><p>木桶原理：组织整体能力水平 = 最短板的能力水平状态</p>' },
      { id: 16, tag: '五星重要', question: '五种规划方法的名字、提出者、年份、核心思想分别是什么？', answer: '<p>口诀：<strong>战企关价扎</strong></p><ul><li><strong>SST</strong> 战略目标集转移：William King · 1978，组织战略集→信息系统战略集的转换</li><li><strong>BSP</strong> 企业系统规划：IBM · 1970s，自顶向下分析需求，自底向上设计结构</li><li><strong>CSF</strong> 关键成功因素：Zani/Rockart · 1970，少数关键成功因素决定信息需求</li><li><strong>VCA</strong> 价值链分析：Porter · 1985，价值链上识别战略环节优先部署IT</li><li><strong>Zachman</strong> 框架：John Zachman · 1987，6W×6层 = 36格的企业架构分类</li></ul>' },
      { id: 17, tag: '高频考点', question: 'BSP企业系统规划法的四个基本步骤是什么？核心理念是什么？', answer: '<p>口诀：<strong>目功数构</strong></p><ol><li><strong>定义管理目标</strong>：采访各级管理层，绘制目标树</li><li><strong>定义管理功能</strong>：基于资源的生命周期识别（产生/获得/服务/归宿）</li><li><strong>定义数据类</strong>：实体法 + 功能法，归纳10~20个数据类</li><li><strong>定义信息结构</strong>：功能/数据类矩阵→C-U矩阵→聚类分组→子系统划分</li></ol><p>核心理念：<strong>管理功能应独立于组织机构</strong>（组织变动不影响系统设计）</p>' },
      { id: 18, tag: '高频考点', question: 'CSF关键成功因素法的四个主要来源和四类CSF分别是什么？', answer: '<p>四个主要来源（口诀：<strong>产竞环暂</strong>）：①个别产业结构 ②竞争策略与产业地位 ③环境因素 ④暂时因素</p><p>四类CSF：<strong>内部型</strong> / <strong>外部型</strong> / <strong>监控型</strong> / <strong>建立型</strong></p><p>四步实施：①确定战略目标 → ②识别所有成功因素 → ③确定关键成功因素 → ④识别绩效指标</p>' },
      { id: 19, tag: '高频考点', question: 'VCA价值链分析法的四个基本观点和四步应用分别是什么？', answer: '<p>四个基本观点：价值核心 / 基本活动+支持活动 / 相互依存 / 竞争优势来自优化</p><p>四步应用：①识别价值链 → ②确定关键价值<strong>增加</strong>环节 → ③确定关键价值<strong>减少</strong>环节 → ④明确IT支持</p>' },
      { id: 20, tag: '高频考点', question: 'Zachman框架的结构是什么？横向6W和纵向6层分别对应什么？', answer: '<p>结构：<strong>6行（纵向）× 6列（横向）= 36格</strong></p><p>横向<strong>6W</strong>：What（数据）/ How（功能）/ Where（网络）/ Who（人员）/ When（时间）/ Why（动机）</p><p>纵向<strong>6层</strong>：范围模型 → 企业模型 → 系统模型 → 技术模型 → 详细模型 → 功能模型</p>' },
    ]
  },

  ch05: {
    title: '第5章 应用系统规划',
    cards: [
      { id: 1, tag: '必须掌握', question: '应用系统规划的9大基本概念是什么？请说出记忆口诀。', answer: '<p>口诀：<strong>抽体模关模信功求重</strong></p><ul><li><strong>抽象</strong>：从众多事物中抽取共同的本质特征</li><li><strong>体系架构</strong>：应用系统的组成结构+交互方式+数据结构</li><li><strong>模式</strong>：最佳实践的表达方法，承载已证实解决方案的精髓</li><li><strong>关注点分离</strong>：将复杂问题分解为可独立解决的若干块</li><li><strong>模块化</strong>：将系统划分为独立命名的、可处理的模块</li><li><strong>信息隐蔽</strong>：每个模块隐蔽自己的规划设计决策（算法和数据）</li><li><strong>功能独立</strong>：通过专一功能、低耦合的模块实现</li><li><strong>求精</strong>：自顶向下逐步分解功能的宏观陈述</li><li><strong>重构</strong>：重新组织以简化设计而不改变功能或行为</li></ul>' },
      { id: 2, tag: '高频考点', question: '四种抽象类型分别是什么？每种抽象的核心要点是什么？', answer: '<p>口诀：<strong>业过数技</strong></p><ul><li><strong>业务抽象</strong>：将复杂业务活动转化为可管控、可显性表达、可重用的业务区块，聚焦价值本质</li><li><strong>过程抽象</strong>：具有明确和有限功能的指令序列，暗示功能但隐藏细节</li><li><strong>数据抽象</strong>：描述数据对象的具体数据集合，如属性的完整定义</li><li><strong>技术抽象</strong>：描述问题解决所需可持续开发利用的技术体系</li></ul>' },
      { id: 3, tag: '高频考点', question: '功能独立的两个定性评估标准是什么？它们的关系是什么？', answer: '<ul><li><strong>内聚性</strong>：模块相关功能的强度（一个内聚模块应只完成一件/一类事情）</li><li><strong>耦合性</strong>：模块间的相互依赖性（应尽力得到最低耦合）</li></ul><p>关系：内聚性越高→独立性越高；耦合性越高→「涟漪效果」越严重</p><p>⚠️ 功能独立是良好规划设计的关键，规划设计又是应用系统质量的关键。</p>' },
      { id: 4, tag: '高频考点', question: '体系架构四种模型分别是什么？各模型的作用是什么？', answer: '<p>口诀：<strong>框动过功</strong></p><ul><li><strong>框架模型</strong>：通过确定相似应用中的可复用架构框架提高抽象级别</li><li><strong>动态模型</strong>：强调架构行为方面，指明结构/配置随外部事件的变化</li><li><strong>过程模型</strong>：强调系统必须提供的业务或技术流程设计</li><li><strong>功能模型</strong>：表示系统的功能层次结构</li></ul>' },
      { id: 5, tag: '高频考点', question: '四种基础架构类型及其核心特点分别是什么？', answer: '<p>口诀：<strong>分数组中</strong></p><ul><li><strong>分层体系</strong>：界面交互层→业务处理层→数据处理层→数据存储层，四层结构</li><li><strong>以数据为中心的架构</strong>：先规划设计好数据环境，再按数据业务应用划分设计各子系统</li><li><strong>客户机/服务器架构</strong>：两层C/S（简单但难维护）→ 三层C/S（集中更新）→ B/S（免客户端）</li><li><strong>组件分布架构</strong>：通过组件集成软件，建立分布式应用系统体系</li></ul>' },
      { id: 6, tag: '高频考点', question: '三大组件分布中间件分别是什么？各由谁提出、有什么特点？', answer: '<p>口诀：<strong>C德E</strong></p><ul><li><strong>CORBA</strong>：通用对象请求代理模型，由<strong>OMG</strong>定义，通用性强，UNIX/Linux/Windows广泛支持</li><li><strong>DCOM</strong>：分布式组件对象模型，由<strong>微软</strong>推出，基于COM，通用性不如CORBA</li><li><strong>EJB</strong>：企业Java Bean，由<strong>Sun</strong>推出，基于Java的分布式组件对象模型</li></ul>' },
      { id: 7, tag: '必须掌握', question: '应用系统规划的五大定义（主要内容）是什么？请说出记忆口诀。', answer: '<p>口诀：<strong>生体接数构</strong></p><p>五大定义：<strong>生命周期选择</strong> → <strong>体系结构定义</strong> → <strong>接口定义</strong> → <strong>数据定义</strong> → <strong>构件定义</strong></p>' },
      { id: 8, tag: '高频考点', question: '四种生命周期模型及其核心特点和适用场景分别是什么？', answer: '<p>口诀：<strong>瀑V迭敏</strong></p><ul><li><strong>瀑布模型</strong>：阶段间顺序依赖、推迟实现、每阶段评审，不适应需求变化</li><li><strong>V模型</strong>：测试活动与分析/设计相关联，编码在顶点，是瀑布变种</li><li><strong>迭代模型</strong>：演化建设或增量建设，缩短面世时间、失败风险低</li><li><strong>敏捷方法</strong>：4核心价值+12原则，个体互动>流程工具，快速响应变化</li></ul>' },
      { id: 9, tag: '高频考点', question: '敏捷宣言的4种核心价值分别是什么？', answer: '<ol><li>个体和互动 <strong>高于</strong> 流程和工具</li><li>工作的软件 <strong>高于</strong> 详尽的文档</li><li>客户合作 <strong>高于</strong> 合同谈判</li><li>响应变化 <strong>高于</strong> 遵循计划</li></ol>' },
      { id: 10, tag: '高频考点', question: '三类接口分别是什么？界面设计的三大黄金原则是什么？', answer: '<p>三类接口（口诀：<strong>用外内</strong>）：用户接口 / 外部接口 / 内部接口</p><p>界面设计三大黄金原则（口诀：<strong>控记一</strong>）：</p><ul><li><strong>置用户于控制之下</strong>：不强迫不必要动作、灵活交互、可中断撤销</li><li><strong>减少用户记忆负担</strong>：减少短期记忆、有意义的默认值、现实世界隐喻</li><li><strong>保持界面一致</strong>：保持语境、不改变已有交互模式</li></ul>' },
      { id: 11, tag: '高频考点', question: '数据库定义的5步骤是什么？口诀？', answer: '<p>口诀：<strong>需概逻物验</strong></p><ol><li><strong>需求分析</strong> → 弄清数据种类/范围/数量，形成用户需求规约</li><li><strong>概念模型</strong> → 抽象概念数据模型，避开计算机实现细节</li><li><strong>逻辑模型</strong> → 转换为特定DBMS支持的逻辑数据模式</li><li><strong>物理数据库</strong> → 选定物理存储结构/存取方法/存取路径</li><li><strong>验证</strong> → 运行典型任务验证正确性和合理性</li></ol>' },
      { id: 12, tag: '五星重要', question: '应用系统主要过程（五步法）是什么？请说出记忆口诀。', answer: '<p>口诀：<strong>初可详分设</strong></p><p>五步链路：<strong>初步调研</strong> → <strong>可行性研究</strong> → <strong>详细调研</strong> → <strong>系统分析</strong> → <strong>系统设计</strong></p><p>⚠️ 5个过程构成完整系统建设链路，是案例和论文的高频考点。</p>' },
      { id: 13, tag: '高频考点', question: '初步调研的5方面内容是什么？口诀？', answer: '<p>口诀：<strong>组环现态资</strong></p><ul><li><strong>组织概况</strong>：规模、历史、行业、管理目标、人力物力</li><li><strong>组织环境</strong>：自然环境、社会经济环境、上下级/横向关系</li><li><strong>现行系统概况</strong>：功能、技术、效率、可靠性、人才、管理体制、问题</li><li><strong>各方面态度</strong>：迫切性、领导决心、人员积极性</li><li><strong>资源情况</strong>：现有/可投入的人力、物力、设备、财力、时间、限制条件</li></ul>' },
      { id: 14, tag: '五星重要', question: '可行性研究的四方面分析分别是什么？口诀？每种分析的核心问题是什么？', answer: '<p>口诀：<strong>经技社管</strong></p><ul><li><strong>经济可行性</strong>：是否值得建设？总成本 vs 总收益（直接效益+间接社会效益）</li><li><strong>技术可行性</strong>：技术资源可用吗？优选成熟技术、慎重引入先进技术</li><li><strong>社会可行性</strong>：与社会环境相符吗？政策/法律/道德/制度/管理/人员+操作可行性</li><li><strong>管理可行性</strong>：领导支持吗？组织领导支持度、管理人员配合度、变革接受度</li></ul><p>三种结论：①可行 ②基本可行需修改 ③不可行不立项</p>' },
      { id: 15, tag: '高频考点', question: '详细调研的6大原则和5种方法分别是什么？', answer: '<p>6大原则（口诀：<strong>自用分工全主</strong>）：自顶向下全面展开 / 用户参与 / 分析改进可能性 / 工程化工作方式 / 全面与重点相结合 / 主动沟通和友善工作方式</p><p>5种方法（口诀：<strong>收发开访深</strong>）：收集资料 / 发调研表 / 开调研会 / 访问 / 深入实际</p>' },
      { id: 16, tag: '高频考点', question: '系统分析的三个阶段分别是什么？口诀？每个阶段的核心工作和输出是什么？', answer: '<p>口诀：<strong>问需定</strong></p><ul><li><strong>问题分析</strong>：需求调研，了解业务 → 输出原始需求</li><li><strong>需求分析</strong>：与用户充分交流，准确完整获取需求 → 输出功能性需求+非功能性需求</li><li><strong>需求定义</strong>：整理并建立最终需求模型 → 输出需求规格说明</li></ul>' },
      { id: 17, tag: '高频考点', question: '四种常用需求分析方法分别是什么？核心模型和口诀是什么？', answer: '<p>口诀：<strong>结信U敏</strong></p><ul><li><strong>面向过程的结构化方法</strong>：自顶向下、逐层分解，核心模型=数据流图</li><li><strong>面向数据的信息工程方法</strong>：以数据为中心，核心模型=实体关系图</li><li><strong>基于UML的用例驱动方法</strong>：兼顾功能+数据，核心模型=用例图+领域类图</li><li><strong>基于敏捷的用户故事</strong>：最轻量级，核心模型=用户故事</li></ul>' },
      { id: 18, tag: '高频考点', question: '系统设计五大评价指标和五大设计原则分别是什么？', answer: '<p>五大评价指标（口诀：<strong>可(靠)可(变)效通质</strong>）：可靠性 / 可变更性 / 效率 / 通用性 / 工作质量</p><p>五大设计原则（口诀：<strong>系灵可经管</strong>）：系统性 / 灵活性 / 可靠性 / 经济性 / 管理可接受</p><p>两个阶段：总体设计（框架概貌）→ 详细设计（具体化、条理化、规范化）</p>' },
      { id: 19, tag: '五星重要', question: '三种常用方法APA/TOGAF/SOA的核心内容分别是什么？请说出记忆口诀。', answer: '<p>口诀：<strong>组框务</strong></p><ul><li><strong>APA应用系统组合法</strong>：评估和管理组织应用系统，确定保留/更新/替换/淘汰。六步（口诀：<strong>清评分策实监</strong>）</li><li><strong>TOGAF开放组架构框架</strong>：ADM全生命周期10阶段+三级迭代。六组件（口诀：<strong>A指内连参能</strong>）</li><li><strong>SOA面向服务的架构</strong>：通过定义良好的接口和契约联系功能单元。六设计原则+六技术内容</li></ul>' },
      { id: 20, tag: '高频考点', question: 'TOGAF ADM全生命周期10阶段分别是什么？', answer: '<p>核心=ADM（架构开发方法），贯穿<strong>需求管理</strong></p><ul><li><strong>预备阶段</strong>：定义组织/架构框架/原则/工具</li><li><strong>A.架构愿景</strong>：设定范围/约束/期望</li><li><strong>B.业务架构</strong>：基线/目标架构描述+差距分析</li><li><strong>C.信息系统架构</strong>：应用架构+数据架构</li><li><strong>D.技术架构</strong>：技术层面架构开发</li><li><strong>E.机会和解决方案</strong>：初步实施规划</li><li><strong>F.迁移规划</strong>：详细实施和迁移计划</li><li><strong>G.实施治理</strong>：架构监督，监测实施</li><li><strong>H.架构变更治理</strong>：持续监测和变更管理</li></ul><p>ADM三级迭代：①架构开发整体迭代 ②多个开发阶段间迭代 ③一个阶段内部迭代</p>' },
      { id: 21, tag: '高频考点', question: 'SOA的六大设计原则和六大技术内容分别是什么？', answer: '<p>六设计原则（口诀：<strong>明自粗松互策</strong>）：明确的接口定义 / 自包含与模块化 / 粗粒度 / 松耦合 / 互操作性兼容性策略声明</p><p>六技术内容（口诀：<strong>封编注治安靠</strong>）：服务封装 / 服务编排 / 服务注册与发现 / 服务治理 / 服务安全 / 服务可靠性和可用性</p><p>五应用场景（口诀：<strong>集流扩云跨</strong>）：组织级应用集成 / 业务流程管理 / 系统扩展和重用 / 云计算和微服务 / 跨平台集成</p>' },
      { id: 22, tag: '高频考点', question: '软件工厂的四大特点和五大构成分别是什么？', answer: '<p>四大特点（口诀：<strong>敏流安协</strong>）：敏捷交付 / 流水线作业 / 安全可靠 / 协同开发</p><p>五大构成（口诀：<strong>人基工流质</strong>）：专业人员 / 基础设施和硬件 / 工具和技术 / 流程规范和方法论 / 质量管理</p><p>建设四支柱（口诀：<strong>组资业体</strong>）：组织建设 / 资源部署 / 业务管理 / 体系保障</p>' },
    ]
  },

  ch06: {
    title: '第6章 云资源规划',
    cards: [
      { id: 1, tag: '必须掌握', question: '云资源规划的定义和五大目标分别是什么？请说出记忆口诀。', answer: '<p>定义：在云计算环境中，对可用的云资源（计算、存储、网络）进行合理有效的管理和分配的过程。</p><p>五大目标（口诀：<strong>效本展靠需</strong>）：</p><ul><li><strong>提高效率</strong>：避免资源浪费和瓶颈</li><li><strong>降低成本</strong>：优化资源配置、精确预测控制成本</li><li><strong>确保可扩展性</strong>：考虑业务增长和变化需求</li><li><strong>提高可靠性和弹性</strong>：合理分配冗余资源、高可用和容灾</li><li><strong>支持业务需求</strong>：深入了解资源类型和性能要求</li></ul>' },
      { id: 2, tag: '必须掌握', question: '云资源规划的七大关键要素和五步基本流程分别是什么？', answer: '<p>七大要素（口诀：<strong>需评预安弹优监</strong>）：业务需求分析 / 资源评估和规划 / 预算管理 / 安全和合规性 / 弹性和可扩展性 / 性能优化 / 监控和管理</p><p>五步流程（口诀：<strong>收评预设优</strong>，循环过程）：</p><ol><li>需求收集 → ②资源评估和规划 → ③预算管理 → ④设计与实施 → ⑤持续优化</li></ol>' },
      { id: 3, tag: '高频考点', question: '三种云计算部署模式的核心属性和特点分别是什么？混合云的关键能力是什么？', answer: '<p>口诀：<strong>公私混</strong></p><ul><li><strong>公有云</strong>：共享资源服务，成本低、扩展好，所有权属云服务商</li><li><strong>私有云</strong>：专有资源池，数据安全性高，需大规模投资（3-5年回收）</li><li><strong>混合云</strong>：公有+私有协同，灵活性+安全性+成本效益平衡</li></ul><p>混合云关键能力：提供<strong>统一的服务体验</strong>——服务门户统一、资源监控界面统一、账户权限统一（不是简单叠加）</p>' },
      { id: 4, tag: '高频考点', question: '云计算的五大内部特征和四大外部特征分别是什么？', answer: '<p>五大内部特征（口诀：<strong>虚弹自多编</strong>）：虚拟化 / 弹性扩展 / 自动化管理 / 多租户支持 / 资源编排和管理</p><p>四大外部特征（口诀：<strong>可安网成</strong>）：可靠性和可用性 / 安全性 / 网络连接性 / 成本效益</p>' },
      { id: 5, tag: '五星重要', question: '四种云计算服务模式的全称、核心内容和主要用户分别是什么？', answer: '<p>口诀：<strong>I P S F</strong></p><ul><li><strong>IaaS</strong>（基础设施即服务）：虚拟化计算资源 → <strong>系统管理员</strong></li><li><strong>PaaS</strong>（平台即服务）：中间件平台 → <strong>开发人员</strong></li><li><strong>SaaS</strong>（软件即服务）：应用程序即服务 → <strong>普通用户</strong></li><li><strong>FaaS</strong>（功能即服务）：将功能拆分为独立可复用函数 → <strong>开发人员</strong></li></ul>' },
      { id: 6, tag: '高频考点', question: '计算资源的五种形态分别是什么？口诀？', answer: '<p>口诀：<strong>虚容裸G弹</strong></p><ul><li><strong>虚拟机（VM）</strong>：物理服务器上创建多个虚拟实例，每个有独立OS和应用</li><li><strong>容器（Container）</strong>：轻量级虚拟化，将应用及依赖打包成独立可执行单元</li><li><strong>裸金属（Bare Metal）</strong>：物理机形态，面向数据库/大数据/AI等高性能场景</li><li><strong>GPU</strong>：高性能图形处理器，用于图形渲染/深度学习/科学计算</li><li><strong>弹性计算资源（ECR）</strong>：根据需求动态分配和释放，自动扩展或收缩</li></ul>' },
      { id: 7, tag: '高频考点', question: '计算资源规划的七种方法和技术分别是什么？口诀？七步关键过程是什么？', answer: '<p>七种方法（口诀：<strong>容性负弹虚自云</strong>）：容量规划 / 性能优化 / 负载均衡 / 弹性伸缩 / 虚拟化和容器化 / 自动化管理 / 云资源管理</p><p>七步关键过程（口诀：<strong>需容服虚安本监</strong>）：需求分析 → 容量规划 → 云服务选择 → 虚拟化策略 → 安全性考虑 → 成本效益分析 → 持续监控维护</p>' },
      { id: 8, tag: '高频考点', question: '存储资源的七种类型分别是什么？请说出口诀和各自特点。', answer: '<p>口诀：<strong>D N S 对云分虚</strong></p><ul><li><strong>DAS</strong>（直接附加存储）：直连主机/服务器，高性能，适合小型环境</li><li><strong>NAS</strong>（网络附加存储）：网络协议文件级访问，适合文件共享/备份</li><li><strong>SAN</strong>（存储区域网络）：专用网络块级存储，适合企业级高性能</li><li><strong>对象存储</strong>：分布式、高扩展性，适合大规模数据存储</li><li><strong>云存储</strong>：云服务商设施，高度可扩展弹性</li><li><strong>分布式文件系统</strong>：跨多节点分布式管理，高可用容错</li><li><strong>虚拟化存储</strong>：物理存储上创建逻辑存储池，灵活管理</li></ul>' },
      { id: 9, tag: '高频考点', question: '存储资源规划的九步关键过程是什么？口诀？', answer: '<p>口诀：<strong>收分技架安容优管评</strong></p><ol><li>收集需求 → ②分析评估 → ③技术选择 → ④架构设计 → ⑤安全规划 → ⑥容量规划 → ⑦性能优化 → ⑧管理监控 → ⑨定期评估调整</li></ol>' },
      { id: 10, tag: '五星重要', question: '云数据中心的四大规划目标、五大要素和七大设计原则分别是什么？', answer: '<p>四目标（口诀：<strong>可扩效安</strong>）：可靠性和可用性 / 可扩展性 / 性能和效率 / 安全和合规性</p><p>五要素（口诀：<strong>面资高按低</strong>）：面向服务 / 资源池化 / 高效智能 / 按需供给 / 低碳环保</p><p>七原则（口诀：<strong>可冗弹性优安灵节扩</strong>）：可用性和冗余性 / 弹性和可扩展性 / 性能优化 / 安全和隐私 / 灵活性和可管理性 / 节能和环保 / 高度可扩展的存储和网络架构</p>' },
      { id: 11, tag: '高频考点', question: '云数据中心六大核心技术分别是什么？网络架构设计的七大要素是什么？', answer: '<p>六技术（口诀：<strong>网融测虚安节</strong>）：网络架构 / 网络融合 / 性能测试 / 虚拟化 / 安全 / 节能</p><p>网络架构七要素（口诀：<strong>扩错时宽模扁绿</strong>）：可扩展性 / 多路径容错 / 低时延 / 高带宽 / 模块化 / 网络扁平化 / 绿色节能</p>' },
      { id: 12, tag: '高频考点', question: '网络性能测试的三个层次和各自指标分别是什么？', answer: '<ul><li><strong>网络层</strong>：连通性、带宽、时延、丢包率</li><li><strong>传输层</strong>：丢包率、吞吐量、连接数</li><li><strong>应用层</strong>：页面丢失率、应答延迟、吞吐量</li></ul><p>两种测试方法：</p><ul><li><strong>主动测试</strong>：部署测试工具，主动发送探测流 → 适合端到端时延、丢包</li><li><strong>被动测试</strong>：被动采集数据 → 适合路径吞吐量等流量参数</li></ul>' },
      { id: 13, tag: '高频考点', question: '四种常用虚拟化技术分别是什么？各有什么特点？', answer: '<p>口诀：<strong>硬全半辅</strong></p><ul><li><strong>硬件仿真技术</strong>：在宿主机OS上创建硬件VM仿真所需硬件</li><li><strong>全虚拟化技术</strong>：软件模拟与真实硬件完全相同的环境，OS无须修改，兼容性好</li><li><strong>半虚拟化技术</strong>：暴露修改过的硬件抽象，以软件形式提供硬件接口</li><li><strong>硬件辅助虚拟化技术</strong>：借助CPU/芯片组/IO设备虚拟化支持实现高效全虚拟化</li></ul>' },
      { id: 14, tag: '高频考点', question: 'PUE是什么？计算公式是什么？PUE值越接近什么越好？', answer: '<p><strong>PUE（电能使用效率）</strong>是评价数据中心能源效率的核心指标。</p><p>计算公式：<strong>PUE = 数据中心总用电量 / IT设备总用电量</strong></p><p>PUE越接近<strong>1</strong>，绿色化程度越高（IT能耗占比100%，无额外能耗浪费）。</p><p>⚠️ 首考案例出现纯计算题，PUE计算是重点。</p>' },
      { id: 15, tag: '高频考点', question: '云数据中心功能定位的四个方向分别是什么？', answer: '<p>口诀：<strong>城边网国</strong></p><ul><li><strong>城市数据中心</strong>：向实时性和弹性化发展，需异地灾备</li><li><strong>边缘数据中心</strong>：计算能力下沉，"云计算+边缘计算"模式</li><li><strong>数据中心和网络协同</strong>：云网边深度融合的算力网络</li><li><strong>国际化数据中心</strong>：自贸区/"一带一路"沿线试点</li></ul>' },
      { id: 16, tag: '高频考点', question: '新基建七大领域分别是什么？数据中心的分级标准有哪些？', answer: '<p>新基建七大领域（口诀：<strong>5特高车大人工</strong>）：5G基站 / 特高压 / 城际高铁和轨交 / 新能源汽车充电桩 / 大数据中心 / 人工智能 / 工业互联网</p><p>分级标准：</p><ul><li><strong>国内</strong>：GB 50174 → A/B/C 三级</li><li><strong>国际</strong>：TIA-942 → T4/T3/T2/T1 四级</li></ul>' },
    ]
  }
}
